Import Packages

In [90]:
from nltk.corpus import wordnet #dictionnary D
import PyDictionary
import pytrec_eval as pe
import BirkBeck #Spelling error C
import _io

corpus = open('BirkBeck/UPWARDDAT.643', 'r')
line = 0
corpus_list = []

while line <= 5:
    read_string = corpus.readline()
    temp_string = read_string.replace('\n', '')
    string = temp_string.split("  ")
    corpus_list.append(string)
    line += 1

print(corpus_list)

[['Eastwood', 'Estwood'], ['Hitler', 'Hitlar'], ["I'd", "I'ld"], ["I've", 'Iev'], ['Ireland', 'Irland'], ['Rolls', 'rowles']]


Minimum Edit Distance Algorithm

In [91]:
def MED(source, target):
    n = len(source)
    m = len(target)
    del_cost = 1
    ins_cost = 1
    sub_cost = 0
    distance = np.zeros([n+1, m+1])

    for i in range(1, n):
        distance[i,0] = distance[i-1, 0] + del_cost
    for j in range(1,m):
        distance[0,j] = distance[0, j-1] + ins_cost

    for i in range(1, n):
        for j in range(1, m):
            if source[n-1] == target[m-1]:
                sub_cost = 0
            else:
                sub_cost = 1
            distance[i,j] = min (   
                                distance[i-1, j] + del_cost,
                                distance[i-1, j-1] + sub_cost,
                                distance[i, j-1] + ins_cost
                                )

    return distance

Test MED function

In [92]:
correct_word = ''
incorrect_word = ''

for i in range (len(corpus_list)):
    print(corpus_list[i])
    correct_word = corpus_list[i][0]
    incorrect_word = corpus_list[i][1]
    print(MED(correct_word, incorrect_word))
    print('\n')

['Eastwood', 'Estwood']
[[0. 1. 2. 3. 4. 5. 6. 0.]
 [1. 0. 1. 2. 3. 4. 5. 0.]
 [2. 1. 0. 1. 2. 3. 4. 0.]
 [3. 2. 1. 0. 1. 2. 3. 0.]
 [4. 3. 2. 1. 0. 1. 2. 0.]
 [5. 4. 3. 2. 1. 0. 1. 0.]
 [6. 5. 4. 3. 2. 1. 0. 0.]
 [7. 6. 5. 4. 3. 2. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


['Hitler', 'Hitlar']
[[0. 1. 2. 3. 4. 5. 0.]
 [1. 0. 1. 2. 3. 4. 0.]
 [2. 1. 0. 1. 2. 3. 0.]
 [3. 2. 1. 0. 1. 2. 0.]
 [4. 3. 2. 1. 0. 1. 0.]
 [5. 4. 3. 2. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


["I'd", "I'ld"]
[[0. 1. 2. 3. 0.]
 [1. 0. 1. 2. 0.]
 [2. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0.]]


["I've", 'Iev']
[[0. 1. 2. 0.]
 [1. 1. 2. 0.]
 [2. 2. 2. 0.]
 [3. 3. 3. 0.]
 [0. 0. 0. 0.]]


['Ireland', 'Irland']
[[0. 1. 2. 3. 4. 5. 0.]
 [1. 0. 1. 2. 3. 4. 0.]
 [2. 1. 0. 1. 2. 3. 0.]
 [3. 2. 1. 0. 1. 2. 0.]
 [4. 3. 2. 1. 0. 1. 0.]
 [5. 4. 3. 2. 1. 0. 0.]
 [6. 5. 4. 3. 2. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


['Rolls', 'rowles']
[[0. 1. 2. 3. 4. 5. 0.]
 [1. 0. 1. 2. 3. 4. 0.]
 [2. 1. 0. 1. 2. 3. 0.]
 [3. 2. 1. 0. 1. 2. 0.]
 [4. 3. 2. 1. 0. 1. 