Import Packages

In [148]:
from nltk.corpus import wordnet
import PyDictionary as pd
import pytrec_eval as pe
import BirkBeck
import numpy as np

Minimum Edit Distance Algorithm

In [149]:
def MED(source, target):
    n = len(source)
    m = len(target)
    del_cost = 1
    ins_cost = 1
    sub_cost = 0
    distance = np.zeros([n+1, m+1])

    for i in range(1, n):
        distance[i,0] = distance[i-1, 0] + del_cost
    for j in range(1,m):
        distance[0,j] = distance[0, j-1] + ins_cost

    for i in range(1, n):
        for j in range(1, m):
            if source[n-1] == target[m-1]:
                sub_cost = 0
            else:
                sub_cost = 1
            distance[i,j] = min (   
                                distance[i-1, j] + del_cost,
                                distance[i-1, j-1] + sub_cost,
                                distance[i, j-1] + ins_cost
                                )

    return distance

Test MED function

In [150]:
print(MED("Python", "Peithen"))

[[0. 1. 2. 3. 4. 5. 6. 0.]
 [1. 0. 1. 2. 3. 4. 5. 0.]
 [2. 1. 0. 1. 2. 3. 4. 0.]
 [3. 2. 1. 0. 1. 2. 3. 0.]
 [4. 3. 2. 1. 0. 1. 2. 0.]
 [5. 4. 3. 2. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
